test:
    SECRET_NAME: github_ci_bot_test_credentials    
    JENKINS_URL: http://jenkins.mxnet-ci-dev.amazon-ml.com/
    SECRET_ENDPOINT_URL: https://secretsmanager.us-west-2.amazonaws.com
    SECRET_ENDPOINT_REGION: us-west-2
    SECRET_ARN: arn:aws:secretsmanager:us-west-2:139068448383:secret:github_ci_bot_test_credentials-ikIwOD 
    LOGGING_LEVEL: DEBUG
    LOGGING_LEVEL_BOTOCORE: INFO
    LOGGING_LEVEL_BOTO3: INFO
    LOGGING_LEVEL_URLLIB3: INFO
    LOGGING_LEVEL_REQUESTS: ERROR
    REPO_NAME: ChaiBapchya/incubator-mxnet

prod:
    # SECRET_NAME: prod/AutoScaling/Jenkins_Credentials
    JENKINS_URL: http://jenkins.mxnet-ci.amazon-ml.com/
    SECRET_ENDPOINT_URL: https://secretsmanager.us-west-2.amazonaws.com
    # SECRET_ARN: arn:aws:secretsmanager:us-west-2:139068448383:secret:github_ci_bot_test_credentials-ikIwOD 
    SECRET_ENDPOINT_REGION: us-west-2
    LOGGING_LEVEL: DEBUG
    LOGGING_LEVEL_BOTOCORE: INFO
    LOGGING_LEVEL_BOTO3: INFO
    LOGGING_LEVEL_URLLIB3: INFO
    LOGGING_LEVEL_REQUESTS: ERROR
    REPO_NAME: apache/incubator-mxnet
